### ISSUE TITLE
Using components like admonition in chapter RST code

### ISSUE THREAD

**Issue by Mankro** [Aalto-LeTech/a-plus-rst-tools#5]
For example, admonition and seealso directives do not work out-of-the-box in A+ chapters since the compiled HTML does not include any CSS rules for styling those components (admonition etc.). You just get the HTML structures of the components but there is no style that affects them. If you compile RST with a standard theme, not the A+ theme, then those components work of course. Is it possible to add such default CSS rules to the A+ RST theme, or should I manually add CSS rules to my course so that admonitions render correctly?

**Comment by teemulehtinen** [comment]
I'm open for adding the default OR subset of sphinx CSS to the sphinx custom A+ theme. If my memory serves me right I cut it out because O1-material redefined most of the CSS and there were body etc level rules in defaults that are potential issue within A+ system. I recommend to test it out and create PR on the option that works for you. You may also look for reference in O1 but it is messy.

**Comment by Mankro** [comment]
I will try to add admonition CSS to the A+ theme in the tools today. I shall avoid body level rules that could easily break other things in A+.
